format = """
[](#232634)\
$directory\
[](fg:#232634 bg:#303446)\
$git_branch\
$git_status\
[](fg:#303446 bg:#86BBD8)\
[](fg:#86BBD8 bg:#06969A)\
[](fg:#06969A bg:#33658A)\
$time\
[ ](fg:#33658A)\
"""

# Disable the blank line at the start of the prompt
add_newline = false
command_timeout = 1000

[directory]
style = "bg:#232634"
format = "[$path ]($style)"
truncation_length = 0
truncation_symbol = ""

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"~/Developer" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[git_branch]
symbol = ""
style = "bg:#303446"
format = '[ $symbol ]($style)'
truncation_length = 10
truncation_symbol = ''

[git_status]
style = "bg:#303446"
ahead = '⇡${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'
format = '[$diverged ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#33658A"
format = '[ $time ]($style)'

