#!/bin/bash

export BG_COLOR=0xff414559
export FG_COLOR=0xffffffff
export ACTIVE_COLOR=0xcc00c1ad

sketchybar --add event aerospace_workspace_change

############## BAR ##############
sketchybar -m --bar height=35 \
    blur_radius=0 \
    position=top \
    padding_left=10 \
    padding_right=10 \
    margin=0 \
    corner_radius=0 \
    color=0x002E3440 \
    border_width=0 \
    border_color=0x00000000

############## GLOBAL DEFAULTS ##############
sketchybar -m --default updates=when_shown \
    drawing=on \
    background.height=35 \
    icon.font="SauceCodePro Nerd Font:Regular:12.0" \
    icon.color=$FG_COLOR \
    icon.highlight_color=0xffA3BE8C \
    label.font="SauceCodePro Nerd Font:Regular:12.0" \
    label.color=$FG_COLOR

sketchybar -m --default label.padding_left=0 \
    label.padding_right=0 \
    icon.padding_left=10 \
    icon.padding_right=10

sketchybar -m --add item logo left \
    --set logo icon= \
    background.color=0xffe78284 \
    background.padding_right=0 \
    click_script="sketchybar -m --update"

# Create workspace items with icons
sketchybar -m --add space space.W left \
    --subscribe space.W aerospace_workspace_change \
    --set space.W \
    associated_display=1 \
    background.drawing=off \
    background.color=$ACTIVE_COLOR \
    icon= \
    click_script="aerospace workspace W" \
    script="$HOME/.config/sketchybar/plugins/aerospace.sh W"

sketchybar -m --add space space.C left \
    --subscribe space.C aerospace_workspace_change \
    --set space.C \
    associated_display=1 \
    background.drawing=off \
    background.color=$ACTIVE_COLOR \
    icon=󰍡 \
    click_script="aerospace workspace C" \
    script="$HOME/.config/sketchybar/plugins/aerospace.sh C"

sketchybar -m --add space space.P left \
    --subscribe space.P aerospace_workspace_change \
    --set space.P \
    associated_display=1 \
    background.drawing=off \
    background.color=$ACTIVE_COLOR \
    icon= \
    click_script="aerospace workspace P" \
    script="$HOME/.config/sketchybar/plugins/aerospace.sh P"

sketchybar -m --add space space.F left \
    --subscribe space.F aerospace_workspace_change \
    --set space.F \
    associated_display=1 \
    background.drawing=off \
    background.color=$ACTIVE_COLOR \
    icon=󰝚 \
    click_script="aerospace workspace F" \
    script="$HOME/.config/sketchybar/plugins/aerospace.sh F"

sketchybar -m --add item clock_logo right --set clock_logo icon=󱑆 \
    background.color=0xff8caaee
sketchybar -m --add item clock right \
    --set clock update_freq=1 \
    script="$HOME/.config/sketchybar/plugins/clock.sh" \
    label.padding_right=10 \
    label.padding_left=0 \
    icon.padding_left=0

sketchybar -m --add item stats_logo right \
    --set stats_logo icon= \
    icon.font="SauceCodePro Nerd Font:Regular:13.0" \
    background.color=0xffef9f76

sketchybar -m --add item ram_label right \
    --set ram_label label.font="SauceCodePro Nerd Font:Regular:11.0" \
    label=RAM \
    y_offset=7 \
    width=0 \
    label.padding_right=10 \
    label.padding_left=0 \
    icon.padding_left=0 \
    \
    --add item ram_percentage right \
    --set ram_percentage label.font="SauceCodePro Nerd Font:Regular:11.0" \
    y_offset=-6 \
    update_freq=1 \
    label.padding_right=10 \
    label.padding_left=0 \
    icon.padding_left=0 \
    script="$HOME/.config/sketchybar/plugins/ram.sh"

sketchybar -m --add item cpu_label right \
    --set cpu_label label.font="SauceCodePro Nerd Font:Regular:11.0" \
    label=CPU \
    y_offset=7 \
    width=0 \
    \
    --add item cpu_percent right \
    --set cpu_percent label.font="SauceCodePro Nerd Font:Regular:11.0" \
    y_offset=-6 \
    update_freq=1 \
    script="$HOME/.config/sketchybar/plugins/cpu.sh"

sketchybar -m --add item network_up right \
    --set network_up label.font="SauceCodePro Nerd Font:Regular:11.0" \
    icon.font="SauceCodePro Nerd Font:Regular:11.0" \
    icon= \
    icon.highlight_color=0xff8b0a0d \
    y_offset=7 \
    width=0 \
    update_freq=1 \
    script="$HOME/.config/sketchybar/plugins/network.sh" \
    \
    --add item network_down right \
    --set network_down label.font="SauceCodePro Nerd Font:Regular:11.0" \
    icon.font="SauceCodePro Nerd Font:Regular:11.0" \
    icon= \
    icon.highlight_color=0xff10528c \
    y_offset=-6 \
    update_freq=1

# Finalize setup
sketchybar --update
